### DISCUSSION TITLE
SkBee loading before Skript [solution]

### DISCUSSION THREAD

**Discussion by WizardWoodland** [ShaneBeee/SkBee#214] [General]
if you have a plugin installed that changes the loading order installed,
(for example, multiverse core) 
then skbee may load before skript and therefore be disabled.

### **BUG solution:**

In the .jar archive of the skbee plugin in the file plugin.yml
### **Replace** 
```yaml
softdepend:
  - Skript
  - FastAsyncWorldEdit
  - skript-variable-dump
loadbefore:
  - SkQuery
```

### **with**
```yaml
depend:
  - Skript
softdepend:
  - FastAsyncWorldEdit
  - skript-variable-dump
loadbefore:
  - SkQuery
```

And it works.
